// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/xince-fun/InstaGo/server/api/conf"
	"github.com/xince-fun/InstaGo/server/api/pkg/initialize"
	"github.com/xince-fun/InstaGo/server/api/pkg/initialize/rpc"
)

func main() {
	initialize.InitLogger()
	initialize.InitConfig()
	r, info := initialize.InitRegistry()
	rpc.InitRPC()
	tracer, trcCfg := hertztracing.NewServerTracer()

	h := server.New(
		tracer,
		server.WithALPN(true),
		server.WithHostPorts(fmt.Sprintf(":%d", conf.GlobalServerConf.Port)),
		server.WithRegistry(r, info),
		server.WithHandleMethodNotAllowed(true),
	)

	h.Use(hertztracing.ServerMiddleware(trcCfg))

	register(h)
	h.Spin()
}
