// Code generated by Kitex v0.9.1. DO NOT EDIT.

package blobservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	blob "github.com/xince-fun/InstaGo/server/shared/kitex_gen/blob"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GeneratePutPreSignedUrl(ctx context.Context, req *blob.GeneratePutPreSignedUrlRequest, callOptions ...callopt.Option) (r *blob.GeneratePutPreSignedUrlResponse, err error)
	GenerateGetPreSignedUrl(ctx context.Context, req *blob.GenerateGetPreSignedUrlRequest, callOptions ...callopt.Option) (r *blob.GenerateGetPreSignedUrlResponse, err error)
	NotifyBlobUpload(ctx context.Context, req *blob.NotifyBlobUploadRequest, callOptions ...callopt.Option) (r *blob.NotifyBlobUploadResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kBlobServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBlobServiceClient struct {
	*kClient
}

func (p *kBlobServiceClient) GeneratePutPreSignedUrl(ctx context.Context, req *blob.GeneratePutPreSignedUrlRequest, callOptions ...callopt.Option) (r *blob.GeneratePutPreSignedUrlResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GeneratePutPreSignedUrl(ctx, req)
}

func (p *kBlobServiceClient) GenerateGetPreSignedUrl(ctx context.Context, req *blob.GenerateGetPreSignedUrlRequest, callOptions ...callopt.Option) (r *blob.GenerateGetPreSignedUrlResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateGetPreSignedUrl(ctx, req)
}

func (p *kBlobServiceClient) NotifyBlobUpload(ctx context.Context, req *blob.NotifyBlobUploadRequest, callOptions ...callopt.Option) (r *blob.NotifyBlobUploadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.NotifyBlobUpload(ctx, req)
}
