// Code generated by Kitex v0.9.1. DO NOT EDIT.
package blobservice

import (
	server "github.com/cloudwego/kitex/server"
	blob "github.com/xince-fun/InstaGo/server/shared/kitex_gen/blob"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler blob.BlobService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler blob.BlobService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
