// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/xince-fun/InstaGo/server/services/relation/app"
	"github.com/xince-fun/InstaGo/server/services/relation/infra/cache"
	"github.com/xince-fun/InstaGo/server/services/relation/infra/persistence"
	"github.com/xince-fun/InstaGo/server/services/relation/infra/persistence/dal"
	"github.com/xince-fun/InstaGo/server/services/relation/infra/sal"
	"github.com/xince-fun/InstaGo/server/services/relation/pkg/initialize"
)

// Injectors from wire.go:

func InitializeService() *RelationServiceImpl {
	db := initialize.InitDB()
	relationDal := dal.NewRelationDal(db)
	relationRepo := persistence.NewRelationRepo(relationDal)
	client := initialize.InitUser()
	userManager := sal.NewUserManager(client)
	cacheCache := cache.NewCache()
	redisManager := cache.NewRedisManager(cacheCache)
	relationApplicationService := app.NewRelationApplicationService(relationRepo, userManager, redisManager)
	relationServiceImpl := NewRelationServiceImpl(relationApplicationService)
	return relationServiceImpl
}
