// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/xince-fun/InstaGo/server/api/biz/router/common"
	"github.com/xince-fun/InstaGo/server/shared/consts"
)

func rootMw() []app.HandlerFunc {
	return common.CommonMW()
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	return nil
}

func _loginMw() []app.HandlerFunc {
	return nil
}

func _registerMw() []app.HandlerFunc {
	return nil
}

func _updateemailMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}

func _updatephoneMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}

func _updatebirthdayMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}

func _updatepasswdMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}
