// Code generated by Kitex v0.9.1. DO NOT EDIT.

package relationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	relation "github.com/xince-fun/InstaGo/server/shared/kitex_gen/relation"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Follow": kitex.NewMethodInfo(
		followHandler,
		newRelationServiceFollowArgs,
		newRelationServiceFollowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Unfollow": kitex.NewMethodInfo(
		unfollowHandler,
		newRelationServiceUnfollowArgs,
		newRelationServiceUnfollowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CountFolloweeList": kitex.NewMethodInfo(
		countFolloweeListHandler,
		newRelationServiceCountFolloweeListArgs,
		newRelationServiceCountFolloweeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CountFollowerList": kitex.NewMethodInfo(
		countFollowerListHandler,
		newRelationServiceCountFollowerListArgs,
		newRelationServiceCountFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFolloweeList": kitex.NewMethodInfo(
		getFolloweeListHandler,
		newRelationServiceGetFolloweeListArgs,
		newRelationServiceGetFolloweeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetFollowerList": kitex.NewMethodInfo(
		getFollowerListHandler,
		newRelationServiceGetFollowerListArgs,
		newRelationServiceGetFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IsFollow": kitex.NewMethodInfo(
		isFollowHandler,
		newRelationServiceIsFollowArgs,
		newRelationServiceIsFollowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	relationServiceServiceInfo                = NewServiceInfo()
	relationServiceServiceInfoForClient       = NewServiceInfoForClient()
	relationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return relationServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return relationServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return relationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RelationService"
	handlerType := (*relation.RelationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "relation",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func followHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceFollowArgs)
	realResult := result.(*relation.RelationServiceFollowResult)
	success, err := handler.(relation.RelationService).Follow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceFollowArgs() interface{} {
	return relation.NewRelationServiceFollowArgs()
}

func newRelationServiceFollowResult() interface{} {
	return relation.NewRelationServiceFollowResult()
}

func unfollowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceUnfollowArgs)
	realResult := result.(*relation.RelationServiceUnfollowResult)
	success, err := handler.(relation.RelationService).Unfollow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceUnfollowArgs() interface{} {
	return relation.NewRelationServiceUnfollowArgs()
}

func newRelationServiceUnfollowResult() interface{} {
	return relation.NewRelationServiceUnfollowResult()
}

func countFolloweeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceCountFolloweeListArgs)
	realResult := result.(*relation.RelationServiceCountFolloweeListResult)
	success, err := handler.(relation.RelationService).CountFolloweeList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceCountFolloweeListArgs() interface{} {
	return relation.NewRelationServiceCountFolloweeListArgs()
}

func newRelationServiceCountFolloweeListResult() interface{} {
	return relation.NewRelationServiceCountFolloweeListResult()
}

func countFollowerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceCountFollowerListArgs)
	realResult := result.(*relation.RelationServiceCountFollowerListResult)
	success, err := handler.(relation.RelationService).CountFollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceCountFollowerListArgs() interface{} {
	return relation.NewRelationServiceCountFollowerListArgs()
}

func newRelationServiceCountFollowerListResult() interface{} {
	return relation.NewRelationServiceCountFollowerListResult()
}

func getFolloweeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceGetFolloweeListArgs)
	realResult := result.(*relation.RelationServiceGetFolloweeListResult)
	success, err := handler.(relation.RelationService).GetFolloweeList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceGetFolloweeListArgs() interface{} {
	return relation.NewRelationServiceGetFolloweeListArgs()
}

func newRelationServiceGetFolloweeListResult() interface{} {
	return relation.NewRelationServiceGetFolloweeListResult()
}

func getFollowerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceGetFollowerListArgs)
	realResult := result.(*relation.RelationServiceGetFollowerListResult)
	success, err := handler.(relation.RelationService).GetFollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceGetFollowerListArgs() interface{} {
	return relation.NewRelationServiceGetFollowerListArgs()
}

func newRelationServiceGetFollowerListResult() interface{} {
	return relation.NewRelationServiceGetFollowerListResult()
}

func isFollowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*relation.RelationServiceIsFollowArgs)
	realResult := result.(*relation.RelationServiceIsFollowResult)
	success, err := handler.(relation.RelationService).IsFollow(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRelationServiceIsFollowArgs() interface{} {
	return relation.NewRelationServiceIsFollowArgs()
}

func newRelationServiceIsFollowResult() interface{} {
	return relation.NewRelationServiceIsFollowResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Follow(ctx context.Context, req *relation.FollowRequest) (r *relation.FollowResponse, err error) {
	var _args relation.RelationServiceFollowArgs
	_args.Req = req
	var _result relation.RelationServiceFollowResult
	if err = p.c.Call(ctx, "Follow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Unfollow(ctx context.Context, req *relation.UnfollowRequest) (r *relation.UnfollowResponse, err error) {
	var _args relation.RelationServiceUnfollowArgs
	_args.Req = req
	var _result relation.RelationServiceUnfollowResult
	if err = p.c.Call(ctx, "Unfollow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountFolloweeList(ctx context.Context, req *relation.CountFolloweeListRequest) (r *relation.CountFolloweeListResponse, err error) {
	var _args relation.RelationServiceCountFolloweeListArgs
	_args.Req = req
	var _result relation.RelationServiceCountFolloweeListResult
	if err = p.c.Call(ctx, "CountFolloweeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountFollowerList(ctx context.Context, req *relation.CountFollowerListRequest) (r *relation.CountFollowerListResponse, err error) {
	var _args relation.RelationServiceCountFollowerListArgs
	_args.Req = req
	var _result relation.RelationServiceCountFollowerListResult
	if err = p.c.Call(ctx, "CountFollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFolloweeList(ctx context.Context, req *relation.GetFolloweeListRequest) (r *relation.GetFolloweeListResponse, err error) {
	var _args relation.RelationServiceGetFolloweeListArgs
	_args.Req = req
	var _result relation.RelationServiceGetFolloweeListResult
	if err = p.c.Call(ctx, "GetFolloweeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFollowerList(ctx context.Context, req *relation.GetFollowerListRequest) (r *relation.GetFollowerListResponse, err error) {
	var _args relation.RelationServiceGetFollowerListArgs
	_args.Req = req
	var _result relation.RelationServiceGetFollowerListResult
	if err = p.c.Call(ctx, "GetFollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsFollow(ctx context.Context, req *relation.IsFollowRequest) (r *relation.IsFollowResponse, err error) {
	var _args relation.RelationServiceIsFollowArgs
	_args.Req = req
	var _result relation.RelationServiceIsFollowResult
	if err = p.c.Call(ctx, "IsFollow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
